# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Tue May 29 21:52:19 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(569, 413)
        MainWindow.setMinimumSize(QtCore.QSize(569, 413))
        MainWindow.setMaximumSize(QtCore.QSize(569, 413))
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Cengiz Kaygusuz - 2012", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../bd.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 531, 221))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 131, 171))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 111, 181))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioMatrix = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioMatrix.setText(QtGui.QApplication.translate("MainWindow", "Denklem takimi coz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioMatrix.setObjectName(_fromUtf8("radioMatrix"))
        self.gridLayout_2.addWidget(self.radioMatrix, 0, 0, 1, 1)
        self.radioMatrix2 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioMatrix2.setText(QtGui.QApplication.translate("MainWindow", "Tersini al", None, QtGui.QApplication.UnicodeUTF8))
        self.radioMatrix2.setObjectName(_fromUtf8("radioMatrix2"))
        self.gridLayout_2.addWidget(self.radioMatrix2, 1, 0, 1, 1)
        self.radioMatrix3 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioMatrix3.setText(QtGui.QApplication.translate("MainWindow", "Determinantini al", None, QtGui.QApplication.UnicodeUTF8))
        self.radioMatrix3.setObjectName(_fromUtf8("radioMatrix3"))
        self.gridLayout_2.addWidget(self.radioMatrix3, 2, 0, 1, 1)
        self.pushBMatrix = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushBMatrix.setText(QtGui.QApplication.translate("MainWindow", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBMatrix.setObjectName(_fromUtf8("pushBMatrix"))
        self.gridLayout_2.addWidget(self.pushBMatrix, 3, 0, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(220, 20, 241, 151))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.DTIn = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.DTIn.setText(QtGui.QApplication.translate("MainWindow", "8 -11 -3", None, QtGui.QApplication.UnicodeUTF8))
        self.DTIn.setObjectName(_fromUtf8("DTIn"))
        self.gridLayout_7.addWidget(self.DTIn, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "   Matris", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.MatrixIn = QtGui.QTextEdit(self.gridLayoutWidget_7)
        self.MatrixIn.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2 1 -1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">-3 -1  2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">-2 1 2</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.MatrixIn.setObjectName(_fromUtf8("MatrixIn"))
        self.gridLayout_7.addWidget(self.MatrixIn, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Denklem T.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.matrixTemizle = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.matrixTemizle.setText(QtGui.QApplication.translate("MainWindow", "Temizle", None, QtGui.QApplication.UnicodeUTF8))
        self.matrixTemizle.setObjectName(_fromUtf8("matrixTemizle"))
        self.gridLayout_7.addWidget(self.matrixTemizle, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 131, 171))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 111, 171))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioRoot = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioRoot.setText(QtGui.QApplication.translate("MainWindow", "Grafik Yontemi", None, QtGui.QApplication.UnicodeUTF8))
        self.radioRoot.setObjectName(_fromUtf8("radioRoot"))
        self.gridLayout.addWidget(self.radioRoot, 0, 0, 1, 1)
        self.radioRoot3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioRoot3.setText(QtGui.QApplication.translate("MainWindow", "Yariya Bolme", None, QtGui.QApplication.UnicodeUTF8))
        self.radioRoot3.setObjectName(_fromUtf8("radioRoot3"))
        self.gridLayout.addWidget(self.radioRoot3, 2, 0, 1, 1)
        self.radioRoot2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioRoot2.setText(QtGui.QApplication.translate("MainWindow", "Regula False", None, QtGui.QApplication.UnicodeUTF8))
        self.radioRoot2.setObjectName(_fromUtf8("radioRoot2"))
        self.gridLayout.addWidget(self.radioRoot2, 1, 0, 1, 1)
        self.radioRoot4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioRoot4.setText(QtGui.QApplication.translate("MainWindow", "Newton-Raphson", None, QtGui.QApplication.UnicodeUTF8))
        self.radioRoot4.setObjectName(_fromUtf8("radioRoot4"))
        self.gridLayout.addWidget(self.radioRoot4, 3, 0, 1, 1)
        self.pushBRoot = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushBRoot.setText(QtGui.QApplication.translate("MainWindow", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBRoot.setObjectName(_fromUtf8("pushBRoot"))
        self.gridLayout.addWidget(self.pushBRoot, 4, 0, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(220, 20, 241, 155))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Fonksiyon", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.RootFIn = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.RootFIn.setText(QtGui.QApplication.translate("MainWindow", "x**2-3*x-28", None, QtGui.QApplication.UnicodeUTF8))
        self.RootFIn.setObjectName(_fromUtf8("RootFIn"))
        self.gridLayout_5.addWidget(self.RootFIn, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Ikincil Deger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Birincil Deger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.Rootx0 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.Rootx0.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.Rootx0.setObjectName(_fromUtf8("Rootx0"))
        self.gridLayout_5.addWidget(self.Rootx0, 2, 1, 1, 1)
        self.Rootx1 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.Rootx1.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.Rootx1.setObjectName(_fromUtf8("Rootx1"))
        self.gridLayout_5.addWidget(self.Rootx1, 3, 1, 1, 1)
        self.kokTemizle = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.kokTemizle.setText(QtGui.QApplication.translate("MainWindow", "Temizle", None, QtGui.QApplication.UnicodeUTF8))
        self.kokTemizle.setObjectName(_fromUtf8("kokTemizle"))
        self.gridLayout_5.addWidget(self.kokTemizle, 6, 0, 1, 2)
        self.RootEpsilon = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.RootEpsilon.setText(QtGui.QApplication.translate("MainWindow", "1e-3", None, QtGui.QApplication.UnicodeUTF8))
        self.RootEpsilon.setObjectName(_fromUtf8("RootEpsilon"))
        self.gridLayout_5.addWidget(self.RootEpsilon, 5, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Epsilon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Max.Adim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 1)
        self.RootMaxIter = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.RootMaxIter.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.RootMaxIter.setObjectName(_fromUtf8("RootMaxIter"))
        self.gridLayout_5.addWidget(self.RootMaxIter, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 131, 171))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 111, 151))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioTurev = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioTurev.setText(QtGui.QApplication.translate("MainWindow", "Yamuk Methodu", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTurev.setObjectName(_fromUtf8("radioTurev"))
        self.gridLayout_3.addWidget(self.radioTurev, 0, 0, 1, 1)
        self.radioTurev2 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioTurev2.setText(QtGui.QApplication.translate("MainWindow", "Simpson Methodu", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTurev2.setObjectName(_fromUtf8("radioTurev2"))
        self.gridLayout_3.addWidget(self.radioTurev2, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.radioInt3 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioInt3.setText(QtGui.QApplication.translate("MainWindow", "Geri Turev", None, QtGui.QApplication.UnicodeUTF8))
        self.radioInt3.setObjectName(_fromUtf8("radioInt3"))
        self.gridLayout_3.addWidget(self.radioInt3, 5, 0, 1, 1)
        self.radioInt2 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioInt2.setText(QtGui.QApplication.translate("MainWindow", "Merkezi Fark", None, QtGui.QApplication.UnicodeUTF8))
        self.radioInt2.setObjectName(_fromUtf8("radioInt2"))
        self.gridLayout_3.addWidget(self.radioInt2, 3, 0, 1, 1)
        self.pushBTurev = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushBTurev.setText(QtGui.QApplication.translate("MainWindow", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBTurev.setObjectName(_fromUtf8("pushBTurev"))
        self.gridLayout_3.addWidget(self.pushBTurev, 7, 0, 1, 1)
        self.radioInt = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioInt.setText(QtGui.QApplication.translate("MainWindow", "Ileri Turev", None, QtGui.QApplication.UnicodeUTF8))
        self.radioInt.setObjectName(_fromUtf8("radioInt"))
        self.gridLayout_3.addWidget(self.radioInt, 4, 0, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(220, 20, 241, 155))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Ikincil Deger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Birincil Deger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.Turevx0 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.Turevx0.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.Turevx0.setObjectName(_fromUtf8("Turevx0"))
        self.gridLayout_6.addWidget(self.Turevx0, 1, 2, 1, 1)
        self.TurevFIn = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.TurevFIn.setText(QtGui.QApplication.translate("MainWindow", "cosh(x)+sinh(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.TurevFIn.setObjectName(_fromUtf8("TurevFIn"))
        self.gridLayout_6.addWidget(self.TurevFIn, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Adim Sayisi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.Turevx1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.Turevx1.setText(QtGui.QApplication.translate("MainWindow", "5*2+sqrt(2)", None, QtGui.QApplication.UnicodeUTF8))
        self.Turevx1.setObjectName(_fromUtf8("Turevx1"))
        self.gridLayout_6.addWidget(self.Turevx1, 2, 2, 1, 1)
        self.TurevMaxIter = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.TurevMaxIter.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.TurevMaxIter.setObjectName(_fromUtf8("TurevMaxIter"))
        self.gridLayout_6.addWidget(self.TurevMaxIter, 3, 2, 1, 1)
        self.TurevEpsilon = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.TurevEpsilon.setText(QtGui.QApplication.translate("MainWindow", "1e-6", None, QtGui.QApplication.UnicodeUTF8))
        self.TurevEpsilon.setObjectName(_fromUtf8("TurevEpsilon"))
        self.gridLayout_6.addWidget(self.TurevEpsilon, 4, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Fonksiyon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Epsilon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 4, 0, 1, 1)
        self.turevTemizle = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.turevTemizle.setText(QtGui.QApplication.translate("MainWindow", "Temizle", None, QtGui.QApplication.UnicodeUTF8))
        self.turevTemizle.setObjectName(_fromUtf8("turevTemizle"))
        self.gridLayout_6.addWidget(self.turevTemizle, 5, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 250, 531, 141))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.textBrowser = QtGui.QTextBrowser(self.gridLayoutWidget_4)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.konsolTemizle = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.konsolTemizle.setText(QtGui.QApplication.translate("MainWindow", "Temizle", None, QtGui.QApplication.UnicodeUTF8))
        self.konsolTemizle.setObjectName(_fromUtf8("konsolTemizle"))
        self.gridLayout_4.addWidget(self.konsolTemizle, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Matris Islemleri", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Kok Bulma", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Turev / Integral", None, QtGui.QApplication.UnicodeUTF8))

